OneKey.Web/Controllers/PasswordController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OneKey.Domain;
using OneKey.ServiceClient;
using OneKey.Shared.Utilities;
using OneKey.Web.ViewModels;
using System.Text.Json;

namespace OneKey.Web.Controllers
{
    public class PasswordController : BaseController
    {
        private readonly IPasswordServiceClient _passwordServiceClient;
        private readonly IIdentityResolver _identityResolver;

        public PasswordController(IMapper mapper,
        ITokenResolver tokenResolver,
        IPayloadResolver payloadResolver,
        IPasswordServiceClient passwordServiceClient,
        IIdentityResolver identityResolver) : base(mapper, tokenResolver, payloadResolver)
        {
            _passwordServiceClient = passwordServiceClient;
            _identityResolver = identityResolver;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var payload = await _payloadResolver.GetPayloadAsync();
            var allPasswords = await _passwordServiceClient.GetAllAsync(payload);
            var viewModel = _mapper.Map<List<PasswordViewModel>>(allPasswords.Value);

            var currentUser = await _identityResolver.GetCurrentAccountAsync();

            if(currentUser.IsSignedIn)
                ViewBag.IsSignedIn = true;

            return View(viewModel);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Upsert(string? reference = "")
        {
            var currentUser = await _identityResolver.GetCurrentAccountAsync();
            if (currentUser.IsSignedIn)
            {
                var viewModel = new PasswordViewModel();
                viewModel.Title = "Create";
                if (!string.IsNullOrWhiteSpace(reference))
                {
                    var payload = await _payloadResolver.GetPayloadAsync();
                    viewModel = _mapper.Map<PasswordViewModel>(await _passwordServiceClient.GetSingleWhereAsync(payload, a => a.Reference == reference));
                    viewModel.Title = "Edit";
                }
               return View(viewModel);
            }
            return View("Index");
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Upsert(PasswordViewModel viewModel)
        {
            var payload = await _payloadResolver.GetPayloadAsync();

            viewModel.StoredPassword = EncodePasswordToBase64(viewModel.StoredPassword);

            if(string.IsNullOrWhiteSpace(viewModel.Reference))
            {
                var result = _passwordServiceClient.CreateAsync(payload, _mapper.Map<PasswordDTO>(viewModel));
            }
            else
            {
                var result = _passwordServiceClient.UpdateAsync(payload, _mapper.Map<PasswordDTO>(viewModel));
            }

            return RedirectToAction("Index");
        }

        private static string EncodePasswordToBase64(string password)
        {

            byte[] encData_byte = new byte[password.Length];
            encData_byte = System.Text.Encoding.UTF8.GetBytes(password);
            string encodedData = Convert.ToBase64String(encData_byte);
            return encodedData;
        }

        private string DecodeFrom64(string encodedData)
        {
            System.Text.UTF8Encoding encoder = new System.Text.UTF8Encoding();
            System.Text.Decoder utf8Decode = encoder.GetDecoder();
            byte[] todecode_byte = Convert.FromBase64String(encodedData);
            int charCount = utf8Decode.GetCharCount(todecode_byte, 0, todecode_byte.Length);
            char[] decoded_char = new char[charCount];
            utf8Decode.GetChars(todecode_byte, 0, todecode_byte.Length, decoded_char, 0);
            string result = new String(decoded_char);
            return result;
        }


        [Authorize]
        public async Task<IActionResult> Filter()
        {
            var payload = await _payloadResolver.GetPayloadAsync();
            var allPasswords = _passwordServiceClient.GetAllAsync(payload);

            var data = JsonConvert.SerializeObject(allPasswords,
                                        new JsonSerializerSettings()
                                        {
                                            ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                                        });

            return Json(data);
        }
    }
}

OneKey.Web/Controllers/UserController.cs
using AutoMapper;
using OneKey.Domain.Models;
using OneKey.ServiceClient;
using OneKey.Shared;
using OneKey.Shared.Utilities;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using OneKey.Web.ViewModels.User;

namespace OneKey.Web.Controllers;

public class UserController : BaseController
{
    private readonly IUserServiceClient _userServiceClient;
    private readonly IIdentityResolver _identityResolver;

    public UserController(IMapper mapper,
        ITokenResolver tokenResolver,
        IPayloadResolver payloadResolver,
        IUserServiceClient userServiceClient,
        IIdentityResolver identityResolver)
        : base(mapper,
            tokenResolver,
            payloadResolver)
    {
        _userServiceClient = userServiceClient;
        _identityResolver = identityResolver;
    }

    [HttpGet("User/Register")]
    public async Task<IActionResult> Register()
    {
        var viewModel = new RegisterUserViewModel {  };
        return View(viewModel);
    }

    [HttpPost("User/Register")]
    public async Task<IActionResult> Register(RegisterUserViewModel viewModel)
    {
        var payload = await _payloadResolver.GetPayloadAsync();

        var userDTO = _mapper.Map<RegisterUserDTO>(viewModel);

        var result = await _userServiceClient.RegisterAsync(payload, userDTO);

        var token = new JwtSecurityTokenHandler().ReadJwtToken(result.Value);

        var identity = new ClaimsPrincipal(new ClaimsIdentity(token.Claims, "OneKey Cookie"));

        await HttpContext.SignInAsync(identity);

        return RedirectToAction("index", "home");
    }

    [HttpGet("User/Login")]
    public async Task<IActionResult> Login()
    {
        var viewModel = new LoginUserViewModel {  };
        return View(viewModel);
    }

    [HttpPost("User/Login")]
    public async Task<IActionResult> Login(LoginUserViewModel viewModel)
    {
        var payload = await _payloadResolver.GetPayloadAsync();

        var userDTO = _mapper.Map<LoginUserDTO>(viewModel);

        var result = await _userServiceClient.LoginAsync(payload, userDTO);

        if (!result.Success)
        {
            viewModel.Failed = true;
            viewModel.ErrorMessage = result.Message;
            
            return View(viewModel);
        }
        
        var token = new JwtSecurityTokenHandler().ReadJwtToken(result.Value);

        var identity = new ClaimsPrincipal(new ClaimsIdentity(token.Claims, "OneKey Cookie"));

        await HttpContext.SignInAsync(identity);

        return RedirectToAction("index", "home");
    }

    [HttpPost("User/Logout")]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();

        return RedirectToAction("index", "home");
    }    
}

OneKey.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OneKey.Web</title>
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/20.2.43/bootstrap5-dark.css" />

    <link rel="stylesheet" href="~/css/bundle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.13.1/datatables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
</head>
<body>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Password" asp-action="Index">Password</a>
                    </li>
                </ul>
                <ul class="navbar-nav pull-right">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
@if (ViewBag.Page == "Login" || ViewBag.Page == "Sign Up")
{
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
}
else
{
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
}
    <script src="~/js/jquery.min.js" type="text/javascript"></script>
    <script src="~/js/bundle.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.13.1/datatables.min.js"></script>
    <script>
        $.onekey.init();
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>